export const GET_COUNT_MEMBERS = "GET_COUNT_MEMBERS";
export const GET_COUNT_MEMBERS_SUCCESS = "GET_COUNT_MEMBERS_SUCCESS";
export const GET_COUNT_COMMISSION = "GET_COUNT_COMMISSION";
export const GET_COUNT_COMMISSION_SUCCESS = "GET_COUNT_COMMISSION_SUCCESS";
export const GET_REFERRAL = "GET_REFERRAL";
export const GET_REFERRAL_SUCCESS = "GET_REFERRAL_SUCCESS";
export const GET_REF_DETAIL_LIST = "GET_REF_DETAIL_LIST";
export const GET_REF_DETAIL_LIST_SUCCESS = "GET_REF_DETAIL_LIST_SUCCESS";
export const GET_SUMARY_COMISSION = "GET_SUMARY_COMISSION";
export const GET_SUMARY_COMISSION_SUCCESS = "GET_SUMARY_COMISSION_SUCCESS";
export const INVITE_FRIEND = "INVITE_FRIEND";
export const GET_BINARY = "GET_BINARY";
export const GET_BINARY_SUCCESS = "GET_BINARY_SUCCESS";

export const GET_BINARY_SPONSOR_F1 = "GET_BINARY_SPONSOR_F1";
export const GET_BINARY_SPONSOR_F1_SUCCESS = "GET_BINARY_SPONSOR_F1_SUCCESS";

export const CHANGE_BINARY_SPONSOR_POSITION = "CHANGE_BINARY_SPONSOR_POSITION";
export const CHANGE_BINARY_SPONSOR_POSITION_SUCCESS = "CHANGE_BINARY_SPONSOR_POSITION_SUCCESS";

export const GET_BINARY_SPONSOR_WITH_POSITION = "GET_BINARY_SPONSOR_WITH_POSITION";
export const GET_BINARY_SPONSOR_WITH_POSITION_SUCCESS = "GET_BINARY_SPONSOR_WITH_POSITION_SUCCESS";

export const INVITE_SPONSOR = "INVITE_SPONSOR";
export const VERIFY_SPONSOR = "VERIFY_SPONSOR";
export const VERIFY_SPONSOR_SUCCESS = "VERIFY_SPONSOR_SUCCESS";
export const VERIFY_SPONSOR_FAIL = "VERIFY_SPONSOR_FAIL";

export const GET_YOUR_NETWORK = "GET_YOUR_NETWORK";
export const GET_YOUR_NETWORK_SUCCESS = "GET_YOUR_NETWORK_SUCCESS";

export const GET_REVENUE = "GET_REVENUE";
export const GET_REVENUE_SUCCESS = "GET_REVENUE_SUCCESS";
export const GET_REFERAL_DETAIL = "GET_REFERAL_DETAIL";
export const GET_REFERAL_DETAIL_SUCCESS = "GET_REFERAL_DETAIL_SUCCESS";
export const OPEN_USER_HISTORY_MODAL = "OPEN_USER_HISTORY_MODAL";
export const GET_USER_WALLET_HISTORY_LIST = "GET_USER_WALLET_HISTORY_LIST";
export const GET_USER_WALLET_HISTORY_LIST_SUCCESS = "GET_USER_WALLET_HISTORY_LIST_SUCCESS";
