export const GET_TRANSACTION_LIST = "GET_TRANSACTION_LIST";
export const GET_TRANSACTION_LIST_SUCCESS = "GET_TRANSACTION_LIST_SUCCESS";
export const CANCEL_TRANSACTION_WITHDRAW = "CANCEL_TRANSACTION_WITHDRAW";
export const CANCEL_TRANSACTION_TRANSFER = "CANCEL_TRANSACTION_TRANSFER";
export const APPROVE_TRANSACTION = "APPROVE_TRANSACTION";
