export const GET_VERIFY_CODE = "GET_VERIFY_CODE";
export const GET_VERIFY_CODE_SUCCESS = "GET_VERIFY_CODE_SUCCESS";
export const UPDATE_KYC = "UPDATE_KYC";
export const UPDATE_KYC_SUCCESS = "UPDATE_KYC_SUCCESS";
export const UPDATE_AUTHY = "UPDATE_AUTHY";
export const REGISTER_AUTHY = "REGISTER_AUTHY";
