export const GET_WALLET_LIST = "GET_WALLET_LIST";
export const GET_WALLET_LIST_SUCCESS = "GET_WALLET_LIST_SUCCESS";

export const GET_LIST_BOUNTY = "GET_LIST_BOUNTY";
export const GET_LIST_BOUNTY_SUCCESS = "GET_LIST_BOUNTY_SUCCESS";

export const POST_FORM_BOUNTY = "POST_FORM_BOUNTY";
