export const GET_WALLET_LIST = "GET_WALLET_LIST";
export const GET_WALLET_LIST_SUCCESS = "GET_WALLET_LIST_SUCCESS";

export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";

export const POST_PRODUCT_LIST = "POST_PRODUCT_LIST";
export const POST_PRODUCT_LIST_SUCCESS = "POST_PRODUCT_LIST_SUCCESS";
